version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=khaddemApp
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER= root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - khaddem

  app:
    image: hamzaabda/spring-new-image
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/khaddemApp?useUnicode=true&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    networks:
      - khaddem
    stdin_open: true
    tty: true
    restart: always

volumes:
  db:
networks:
  khaddem:
