version: '3.1'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - achrafabbes5sae2-g6_default

  myphpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myphpmyadmin
    ports:
      - "9999:80"
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_ARBITRARY: 1
    networks:
      - achrafabbes5sae2-g6_default

  etudiant-container:
    image: etudiant
    container_name: etudiant-container
    ports:
      - 8089:8089
    build:
      context: .
    networks:
      - achrafabbes5sae2-g6_default

networks:
  achrafabbes5sae2-g6_default:
    external: true

volumes:
  db: