version: "3.9"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/vagrant/datadir:/var/lib/mysql
    networks:
      - 5sae2-g6-khadem_default

  spring_app:
    container_name: contrat
    image: contrat
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/khaddemApp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - 5sae2-g6-khadem_default
networks:
  5sae2-g6-khadem_default:
