version: '3.1'
services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /home/vagrant/datadir:/var/lib/mysql

  spring_app:
    image: contrat
    container_name: contrat
    ports:
      - 8089:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/khaddemApp
    depends_on:
      - mysqldb

  angular_app:
    image: khademfront:latest
    container_name: khademfront
    ports:
      - 8082:80