version: "3.9"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/vagrant/datadir:/var/lib/mysql

  spring_app:
    container_name: tpachat
    image: tpachat
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb/khaddemApp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
